apiVersion: v1
kind: Service
metadata:
  namespace: "{$PROJECTNAME}"
  name: "app"
spec:
  selector:
    app: "app"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  namespace: "{$PROJECTNAME}"
  name: "app"
  labels:
    app: "app"
spec:
  hostAliases:
    - ip: "127.0.0.1"
      hostnames:
        - "php"
        - "mail"
  initContainers:
    - name: init-env
      image: busybox
      command: ['sh', '-c', 'printenv | egrep -v ^HOME= > /volume/php/environment']
      volumeMounts:
        - name: "pv"
          mountPath: /volume
          subPath: container
      envFrom:
        - configMapRef:
            name: "{$PROJECTNAME}"
    - name: init-app
      image: busybox
      command: ['sh', '-c', 'chown -R www-data:www-data /volume/htdocs; chmod -R 775 /volume/htdocs']
      volumeMounts:
        - name: pv
          mountPath: /volume
    - name: init-mail
      image: busybox
      command: ['sh', '-c', 'chown -R 104:108 /volume/logs/mail']
      volumeMounts:
        - name: pv
          mountPath: /volume/logs/mail
          subPath: logs/mail

  containers:
    - name: mail
      image: "nibirrayy/docker-smtp"
      imagePullPolicy: Always
      env:
        - name: MAILNAME
          valueFrom:
            configMapKeyRef:
              key: MAIL_DOMAIN
              name: "{$PROJECTNAME}"
      volumeMounts:
        - name: pv
          mountPath: /var/log/exim4
          subPath: logs/mail

    - name: php
      image: "fduarte42/docker-php:{$PHP_VERSION}"
      imagePullPolicy: Always
      volumeMounts:
        - name: "ssh-pv"
          mountPath: /ssh
        - name: "pv"
          mountPath: /etc/environment
          subPath: container/php/environment
        - name: "pv"
          mountPath: /etc/apache2/sites-enabled
          subPath: container/apache2/sites-enabled
        - name: "pv"
          mountPath: /usr/local/etc/php/conf.d/zzz-custom.ini
          subPath: container/php/php.default.ini
        - name: "pv"
          mountPath: /etc/ssmtp/ssmtp.conf
          subPath: container/php/ssmtp.default.conf
        - name: "pv"
          mountPath: /tmp/crontab
          subPath: container/php/crontab.default
        - name: "pv"
          mountPath: /var/www/html
          subPath: "{$HTDOCS_FOLDER}"
        - name: "pv"
          mountPath: /var/log/apache
          subPath: logs/apache
      envFrom:
        - configMapRef:
            name: "{$PROJECTNAME}"
      ports:
        - containerPort: 80
  volumes:
    - name: "pv"
      hostPath:
        path: "{$CWD}"
    - name: "ssh-pv"
      secret:
        secretName: "ssh"