apiVersion: v1
kind: Service
metadata:
  namespace: "{$PROJECTNAME}"
  name: "app"
spec:
  selector:
    app: "app"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: mailhog
      protocol: TCP
      port: 8025
      targetPort: 8025
---
apiVersion: v1
kind: Pod
metadata:
  namespace: "{$PROJECTNAME}"
  name: "app"
  labels:
    app: "app"
spec:
  hostAliases:
    - ip: "127.0.0.1"
      hostnames:
        - "php"
        - "mail"
  initContainers:
    - name: init-env
      image: busybox
      command: ['sh', '-c', 'printenv | egrep -v ^HOME= > /volume/php/environment']
      volumeMounts:
        - name: "pv"
          mountPath: /volume
          subPath: container
      envFrom:
        - configMapRef:
            name: "{$PROJECTNAME}"
  containers:
    - name: mail
      image: "mailhog/mailhog"
      imagePullPolicy: Always
      ports:
        - containerPort: 1025
        - containerPort: 8025

    - name: magic-sync
      image: mickaelperrin/docker-magic-sync:latest
      volumeMounts:
        - name: "htdocs"
          mountPath: /src
        - name: "pv"
          mountPath: /src.magic
          subPath: "{$HTDOCS_FOLDER}"
        - name: "dockersock"
          mountPath: /tmp/docker.sock
      env:
        - name: SYNC_USER
          value: www-data
        - name: SYNC_UID
          value: "33"
        - name: SYNC_IGNORE_NAMES
          value: ".idea:.git"
        - name: MAXIMUM_INOTIFY_WATCHES
          value: "524288"
      securityContext:
        privileged: true

    - name: php
      image: "fduarte42/docker-php:{$PHP_VERSION}-debug"
      imagePullPolicy: Always
      volumeMounts:
        - name: "ssh-pv"
          mountPath: /ssh
        - name: "pv"
          mountPath: /etc/environment
          subPath: container/php/environment
        - name: "pv"
          mountPath: /etc/apache2/sites-enabled
          subPath: container/apache2/sites-enabled
        - name: "pv"
          mountPath: /usr/local/etc/php/conf.d/zzz-custom.ini
          subPath: container/php/php.development.ini
        - name: "pv"
          mountPath: /etc/ssmtp/ssmtp.conf
          subPath: container/php/ssmtp.development.conf
        - name: "pv"
          mountPath: /tmp/crontab
          subPath: container/php/crontab.default
        - name: "pv"
          mountPath: /var/www/html
          subPath: "{$HTDOCS_FOLDER}"
        - name: "pv"
          mountPath: /var/log/apache
          subPath: logs/apache
      envFrom:
        - configMapRef:
            name: "{$PROJECTNAME}"
      ports:
        - containerPort: 80
  volumes:
    - name: "pv"
      hostPath:
        path: "{$CWD}"
    - name: "ssh-pv"
      secret:
        secretName: "ssh"
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: "htdocs"
      emptyDir: {}
