apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert-db
  namespace: "{$PROJECTNAME}"
spec:
  dnsNames:
    - "phpmyadmin.{$BASE_DOMAIN}"
    - "phpmyadmin.neu.{$BASE_DOMAIN}"
  secretName: tls-secret-db
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "{$PROJECTNAME}"
  name: "db-ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/whitelist-source-range: "{$PHPMYADMIN_IP_RESTRICTION}"
    ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/whitelist-source-range: "{$PHPMYADMIN_IP_RESTRICTION}"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
spec:
  tls:
    - hosts:
        - "phpmyadmin.{$BASE_DOMAIN}"
        - "phpmyadmin.neu.{$BASE_DOMAIN}"
      secretName: tls-secret-db
  rules:
    - host: "phpmyadmin.{$BASE_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: "db"
                port:
                  number: 80
    - host: "phpmyadmin.neu.{$BASE_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: "db"
                port:
                  number: 80
