apiVersion: v1
kind: Service
metadata:
  name: "{$PROJECTNAME}-mysql-service"
spec:
  selector:
    app: "{$PROJECTNAME}-db-app"
  type: LoadBalancer
  ports:
    - name: mysql
      port: {$MYSQL_PORT}
      targetPort: mysql