version: '2'
services:
  db:
    image: mysql:5.5
    volumes:
      - "./docker-data/volumes/mysql:/var/lib/mysql"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    links:
      - db:db
    environment:
      PMA_HOST: db
      PHP_UPLOAD_MAX_FILESIZE: "500M"

#  postfix:
#    build: docker-data/container/postfix
#    volumes:
#      - "./docker-data/volumes/postfix/log:/var/log"
#    environment:
#      MYHOSTNAME: localhost
#      MYNETWORKS: 0.0.0.0/0

  smtp:
    image: namshi/smtp

  php:
    depends_on:
      - db
      - phpmyadmin
      - smtp
    build: docker-data/container/php
    links:
      - db:db
      - smtp:mail
    volumes:
      - "./htdocs:/var/www/html"
    restart: always
