version: '2'
services:
  db:
    image: mysql:5.5
    volumes:
      - "./docker-data/volumes/mysql:/var/lib/mysql"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    links:
      - db:db
    environment:
      PMA_HOST: db
      PHP_UPLOAD_MAX_FILESIZE: "500M"

  mail:
    image: mailhog/mailhog

  php:
    depends_on:
      - db
      - phpmyadmin
      - mail
    build: docker-data/container/php
    links:
      - db:db
      - mail:mail
    volumes:
      - "./htdocs:/var/www/html"
    restart: always
