version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "../volumes/nginx/docker_proxy.conf:/etc/nginx/conf.d/docker_proxy.conf:ro"
      - "../volumes/nginx/docker-ui.local.orangehive.de_location:/etc/nginx/vhost.d/docker-ui.local.orangehive.de_location:ro"
    ports:
      - "${PROXY_PORT}:80"
    networks:
      - "frontend-tier"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "nginx-proxy"

  ui:
    image: uifd/ui-for-docker
    container_name: ui-for-docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      VIRTUAL_PORT: 9000
      VIRTUAL_HOST: docker-ui.local.orangehive.de
    networks:
      - "frontend-tier"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "docker-ui"

  graylog:
    image: graylog2/allinone
    container_name: graylog
    ports:
      - "12201:12201/udp"
    environment:
      VIRTUAL_PORT: 9000
      VIRTUAL_HOST: graylog.local.orangehive.de
      GRAYLOG_PASSWORD: ${GRAYLOG_ADMIN_PASSWORD}
    networks:
      - "frontend-tier"

networks:
  frontend-tier:
    external:
      name: proxy

