version: '2'
services:
  db:
    image: mysql:5.5
    volumes:
      - "../volumes-live/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - "backend-tier"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db:db
    environment:
      MYSQL_HOST: db
      UPLOAD_SIZE: "500M"
      MYSQL_ROOT_PASSWORD: 123456
      VIRTUAL_HOST: phpmyadmin.domain.tld
      VIRTUAL_PORT: 80
    networks:
      - "frontend-tier"
      - "backend-tier"
    restart: always

  mail:
    image: fduarte42/docker-postfix
    volumes:
      - "../volumes-live/postfix/log:/var/log"
    environment:
      MYHOSTNAME: domain.tld
      MYNETWORKS: 0.0.0.0/0
    networks:
      - "frontend-tier"
      - "backend-tier"
    restart: always

  php:
    depends_on:
      - db
      - phpmyadmin
      - mail
    image: fduarte42/docker-php:7.0
    links:
      - db:db
      - mail:mail
    volumes:
      - "../volumes-live/php/apache2/vhost.conf:/etc/apache2/sites-enabled/vhost.conf"
      - "../volumes-live/php/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "../volumes-live/php/ssh:/ssh"
      - "../../htdocs:/var/www/html"
    environment:
      VIRTUAL_HOST: domain.tld, www.domain.tld
      VIRTUAL_PORT: 80
    networks:
      - "frontend-tier"
      - "backend-tier"
    restart: always

networks:
  frontend-tier:
    external:
      name: proxy
  backend-tier:
    driver: bridge
