version: '2'
services:
  db:
    image: mysql:5.5
    volumes:
      - "./docker-data/volumes/mysql:/var/lib/mysql"
    networks:
      - "backend-tier"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db:db
    environment:
      MYSQL_HOST: db
      UPLOAD_SIZE: "500M"
      VIRTUAL_PORT: 80
    networks:
      - "frontend-tier"
      - "backend-tier"

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_PORT: 8025
    networks:
      - "frontend-tier"
      - "backend-tier"

  php:
    depends_on:
      - db
      - phpmyadmin
      - mail
    image: fduarte42/docker-php:7.0
    links:
      - db:db
      - mail:mail
    volumes:
      - "./docker-data/volumes/php/apache2/vhost.conf:/etc/apache2/sites-enabled/vhost.conf"
      - "./docker-data/volumes/php/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "./docker-data/volumes/php/ssh:/ssh"
      - "./htdocs:/var/www/html"
    environment:
      VIRTUAL_PORT: 80
    networks:
      - "frontend-tier"
      - "backend-tier"

networks:
  frontend-tier:
    external:
      name: proxy
  backend-tier:
    driver: bridge

