version: '2'
services:
  db:
    image: 'mysql:${MYSQL_VERSION}'
    volumes:
      - "../volumes/mysql:/var/lib/mysql"
    environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - "backend-tier"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - "../volumes/phpmyadmin/php.ini:/etc/php5/conf.d/custom.ini"
    environment:
      MYSQL_HOST: db
      UPLOAD_SIZE: "500M"
      VIRTUAL_PORT: 80
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      VIRTUAL_HOST: ${PHPMYADMIN_VIRTUAL_HOST}
    networks:
      - "frontend-tier"
      - "backend-tier"

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_PORT: 8025
      VIRTUAL_HOST: ${MAIL_VIRTUAL_HOST}
    networks:
      - "frontend-tier"
      - "backend-tier"

  php:
    depends_on:
      - db
      - phpmyadmin
      - mail
    image: 'fduarte42/docker-php:${PHP_VERSION}'
    links:
      - db:db
      - mail:mail
    volumes:
      - "../volumes/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "../volumes/php/apache2/vhost.conf:/etc/apache2/sites-enabled/vhost.conf"
      - "../volumes/php/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "../volumes/php/ssh:/ssh"
      - "../volumes/php/cron/crontab:/tmp/crontab"
      - "../../${HTDOCS_FOLDER}:/var/www/html"
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ${PHP_VIRTUAL_HOST}
      APACHE_HOST: www.${BASE_DOMAIN}
      APACHE_ALIAS: www.${SECONDARY_DOMAIN}
      BASE_DOMAIN: ${BASE_DOMAIN}
      SECONDARY_DOMAIN: ${SECONDARY_DOMAIN}
      DOCUMENT_ROOT: ${DOCUMENT_ROOT}
      APP_ENV: ${ENVIRONMENT}
      APPLICATION_ENVIRONMENT: ${ENVIRONMENT}
      TYPO3_CONTEXT: ${ENVIRONMENT}
    networks:
      - "frontend-tier"
      - "backend-tier"

networks:
  frontend-tier:
    external:
      name: proxy
  backend-tier:
    driver: bridge

