version: '2'
services:
  db:
    image: 'mysql:${MYSQL_VERSION}'
    volumes:
      - "../volumes/mysql:/var/lib/mysql"
    environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - "backend-tier"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db:db
    environment:
      MYSQL_HOST: db
      UPLOAD_SIZE: "500M"
      VIRTUAL_PORT: 80
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      VIRTUAL_HOST: phpmyadmin.${BASE_DOMAIN}
    networks:
      - "frontend-tier"
      - "backend-tier"

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_PORT: 8025
      VIRTUAL_HOST: mailhog.${BASE_DOMAIN}
    networks:
      - "frontend-tier"
      - "backend-tier"

  php:
    depends_on:
      - db
      - phpmyadmin
      - mail
    image: 'fduarte42/docker-php:${PHP_VERSION}'
    links:
      - db:db
      - mail:mail
    volumes:
      - "../volumes/php/apache2/vhost.conf:/etc/apache2/sites-enabled/vhost.conf"
      - "../volumes/php/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "../volumes/php/ssh:/ssh"
      - "../../htdocs:/var/www/html"
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: www.${BASE_DOMAIN}
    networks:
      - "frontend-tier"
      - "backend-tier"

networks:
  frontend-tier:
    external:
      name: proxy
  backend-tier:
    driver: bridge

