version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    ports:
      - "80:80"
    networks:
      - "frontend-tier"

  ui:
    image: uifd/ui-for-docker
    container_name: ui-for-docker
    depends_on:
      - "nginx"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9000:9000"
    networks:
      - "frontend-tier"

networks:
  frontend-tier:
    external:
      name: proxy

