apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: docker
  name: "proxy-compat"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "*.lvh.me"
      http:
        paths:
          - path: /
            backend:
              serviceName: "proxy-compat"
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: docker
  name: "proxy-compat"
spec:
  selector:
    app: "proxy-compat"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  namespace: docker
  name: "proxy-compat"
  labels:
    app: "proxy-compat"
spec:
  containers:
    - name: proxy
      securityContext:
        privileged: true
      image: "jwilder/nginx-proxy"
      imagePullPolicy: Always
      volumeMounts:
        - name: dockersock
          mountPath: "/tmp/docker.sock"
      ports:
        - containerPort: 80
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock