version: '3.5'
services:
  db:
    ports:
      - "${MYSQL_PORT}"
    restart: always

  phpmyadmin:
    restart: always

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: mail.${BASE_DOMAIN:-""}
    restart: always

  php:
    image: 'fduarte42/docker-php:${PHP_VERSION}-debug'
    volumes:
      - "../container/php/php.development.ini:/usr/local/etc/php/conf.d/zzz-custom.ini"
      - "../container/php/ssmtp.development.conf:/etc/ssmtp/ssmtp.conf"
      - htdocs-volume:/var/www/html
    restart: always

  magic-sync:
    image: mickaelperrin/docker-magic-sync:latest
    environment:
      - SYNC_USER=www-data
      - SYNC_UID=33
      - SYNC_IGNORE_NAMES=.idea:.git
      - MAXIMUM_INOTIFY_WATCHES=524288
    volumes:
      - htdocs-volume:/src
      - "../${HTDOCS_FOLDER}:/src.magic:cached"
      - /var/run/docker.sock:/tmp/docker.sock:ro
    privileged: true
    restart: always

volumes:
  htdocs-volume: