version: '3.5'
services:
  init-php:
    image: busybox
    command: ['sh', '-c', 'printenv | egrep -v ^HOME= > /volume/php/environment; chown -R www-data:www-data /volume/htdocs; chmod -R 775 /volume/htdocs']
    environment:
      APACHE_HOST: www.${BASE_DOMAIN}
      APACHE_ALIAS: ${PHP_APACHE_ALIAS:-"localhost"}
      BASE_DOMAIN: ${BASE_DOMAIN}
      DOCUMENT_ROOT: ${DOCUMENT_ROOT}
      APP_ENV: ${ENVIRONMENT}
      APPLICATION_ENVIRONMENT: ${ENVIRONMENT}
      TYPO3_CONTEXT: ${ENVIRONMENT}
      MAIL_DOMAIN: ${BASE_DOMAIN}
      MYSQL_HOST: "db"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./container:/volume"
      - "./${HTDOCS_FOLDER}:/volume/htdocs"
    restart: on-failure

  init-mail:
    image: busybox
    command: ['sh', '-c', 'chown -R 104:108 /volume/logs/mail']
    volumes:
      - "./logs/mail:/volume/logs/mail"
    restart: on-failure

  db:
    image: 'mysql:${MYSQL_VERSION}'
    entrypoint: ["docker-entrypoint.sh", "--default-authentication-plugin", "mysql_native_password", "--max-allowed-packet", "16M"]
    volumes:
      - "./container/mysql/data:/var/lib/mysql"
      - "./container/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - "backend-tier"

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}'
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - "./container/phpmyadmin/php.ini:/etc/php5/conf.d/zzz-custom.ini"
    environment:
      MYSQL_HOST: "db"
      UPLOAD_LIMIT: "500M"
      VIRTUAL_PORT: 80
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      VIRTUAL_HOST: ${PHPMYADMIN_VIRTUAL_HOST:-""}
    networks:
      - "frontend-tier"
      - "backend-tier"

  mail:
    depends_on:
      - init-mail
    image: nibirrayy/docker-smtp
    environment:
      MAILNAME: "${PROJECTNAME}"
    networks:
      - "backend-tier"
    volumes:
      - "./logs/mail:/var/log/exim4"

  php:
    depends_on:
      - init-php
      - db
      - phpmyadmin
      - mail
    image: 'fduarte42/docker-php:${PHP_VERSION}'
    links:
      - db:db
      - mail:mail
      - mail:mailhog
    volumes:
      - "./container/php/php.default.ini:/usr/local/etc/php/conf.d/zzz-custom.ini"
      - "./container/apache2/sites-enabled:/etc/apache2/sites-enabled"
      - "./container/php/ssmtp.default.conf:/etc/ssmtp/ssmtp.conf"
      - "~/.ssh:/ssh"
      - "./container/php/crontab.default:/tmp/crontab"
      - "./container/php/environment:/etc/environment"
      - "./${HTDOCS_FOLDER}:/var/www/html"
      - "./logs/apache:/var/log/apache"
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ${PHP_VIRTUAL_HOST:-""}
      APACHE_HOST: www.${BASE_DOMAIN}
      APACHE_ALIAS: ${PHP_APACHE_ALIAS:-"localhost"}
      BASE_DOMAIN: ${BASE_DOMAIN}
      DOCUMENT_ROOT: ${DOCUMENT_ROOT}
      APP_ENV: ${ENVIRONMENT}
      APPLICATION_ENVIRONMENT: ${ENVIRONMENT}
      TYPO3_CONTEXT: ${ENVIRONMENT}
      MAIL_DOMAIN: ${BASE_DOMAIN}
      MYSQL_HOST: "db"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - "frontend-tier"
      - "backend-tier"

networks:
  frontend-tier:
    name: proxy
  backend-tier:
    driver: bridge

