version: '2.1'
services:
  nginx:
    image: fduarte42/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"
    networks:
      - "frontend-tier"

networks:
  frontend-tier:
    name: proxy
