version: '3.5'
services:
  db:
    ports:
      - "${MYSQL_PORT}"
    restart: always

  phpmyadmin:
    restart: always

  mail:
    image: ajoergensen/mailhog
    environment:
      VIRTUAL_PORT: 8025
      VIRTUAL_HOST: mail.${BASE_DOMAIN:-""}
    networks:
      - "frontend-tier"
    restart: always

  php:
    image: 'fduarte42/docker-php:${PHP_VERSION}-debug'
    volumes:
      - "./container/php/php.dev.ini:/usr/local/etc/php/conf.d/zzz-custom.ini"
      - "./container/php/ssmtp.dev.conf:/etc/ssmtp/ssmtp.conf"
    restart: always
