apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{$PROJECTNAME}-container-pv-volume"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{$CWD}/container"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{$PROJECTNAME}-container-pv-claim"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
