apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{$PROJECTNAME}-htdocs-pv-volume"
  namespace: ingress-nginx
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{$CWD}/{$HTDOCS_FOLDER}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{$PROJECTNAME}-htdocs-pv-claim"
  namespace: ingress-nginx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
