apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{$PROJECTNAME}"
  name: "{$PROJECTNAME}"
data:
  APACHE_HOST: "www.{$BASE_DOMAIN}"
  APPLICATION_ENVIRONMENT: "{$ENVIRONMENT}"
  APP_ENV: "{$ENVIRONMENT}"
  BASE_DOMAIN: "{$BASE_DOMAIN}"
  MAIL_DOMAIN: "www.{$BASE_DOMAIN}"
  DOCUMENT_ROOT: "{$DOCUMENT_ROOT}"
  MYSQL_HOST: "db"
  MYSQL_ROOT_PASSWORD: "{$MYSQL_ROOT_PASSWORD}"
  PIMCORE_ENVIRONMENT: "{$ENVIRONMENT}"
  TYPO3_CONTEXT: "{$ENVIRONMENT}"
