version: '2.1'
services:
  db:
    image: 'mysql:${MYSQL_VERSION}'
    volumes:
      - "../../volumes/mysql/data:/var/lib/mysql"
      - "../container/mysql/config/my.cnf:/etc/mysql/conf.d/custom.cnf"
    environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - "backend-tier"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "mysql"

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}'
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - "../container/phpmyadmin/php.ini:/etc/php5/conf.d/zzz-custom.ini"
    environment:
      MYSQL_HOST: db
      UPLOAD_SIZE: "500M"
      VIRTUAL_PORT: 80
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      VIRTUAL_HOST: ${PHPMYADMIN_VIRTUAL_HOST:-""}
    networks:
      - "frontend-tier"
      - "backend-tier"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "phpmyadmin"

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_PORT: 8025
      VIRTUAL_HOST: ${MAIL_VIRTUAL_HOST:-""}
    networks:
      - "frontend-tier"
      - "backend-tier"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "mail"

  php:
    depends_on:
      - db
      - phpmyadmin
      - mail
    image: 'fduarte42/docker-php:${PHP_VERSION}'
    links:
      - db:db
      - mail:mail
      - mail:mailhog
    volumes:
      - "../container/php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini"
      - "../container/php/apache2/sites-enabled:/etc/apache2/sites-enabled"
      - "../container/php/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "../container/php/ssh:/ssh"
      - "../container/php/cron/crontab:/tmp/crontab"
      - "../../../${HTDOCS_FOLDER}:/var/www/html"
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ${PHP_VIRTUAL_HOST:-""}
      APACHE_HOST: www.${BASE_DOMAIN}
      APACHE_ALIAS: ${PHP_APACHE_ALIAS:-"localhost"}
      BASE_DOMAIN: ${BASE_DOMAIN}
      DOCUMENT_ROOT: ${DOCUMENT_ROOT}
      APP_ENV: ${ENVIRONMENT}
      APPLICATION_ENVIRONMENT: ${ENVIRONMENT}
      TYPO3_CONTEXT: ${ENVIRONMENT}
    networks:
      - "frontend-tier"
      - "backend-tier"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "php"

networks:
  frontend-tier:
    external:
      name: proxy
  backend-tier:
    driver: bridge

