version: '2'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    environment:
      VIRTUAL_HOST: phpmyadmin.template.local.orangehive.de

  mail:
    environment:
      VIRTUAL_HOST: mailhog.template.local.orangehive.de

  php:
    image: fduarte42/docker-php:7.0
    environment:
      VIRTUAL_HOST: www.template.local.orangehive.de
