version: '3'
services:
  db:
    volumes:
      - "../volumes/mysql/init:/docker-entrypoint-initdb.d"

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_PORT: 8025
      VIRTUAL_HOST: ${MAIL_VIRTUAL_HOST:-""}
    networks:
      - "frontend-tier"
      - "backend-tier"

  php:
    image: 'fduarte42/docker-php:${PHP_VERSION}-debug'
    environment:
      XDEBUG_REMOTE_HOST: 'host.docker.internal'
