version: '2'
services:
  db:
    image: mysql:5.5
    volumes:
      - "./docker-data/volumes/mysql:/var/lib/mysql"
    restart: always

  phpmyadmin:
    image: nazarpc/phpmyadmin
    depends_on:
      - db
    restart: always
    links:
      - db:db
    environment:
      MYSQL_HOST: db
      UPLOAD_SIZE: "500M"

  mail:
    image: mailhog/mailhog

  php:
    depends_on:
      - db
      - phpmyadmin
      - mail
    build:
      context: docker-data/container/php70
    links:
      - db:db
      - mail:mail
    volumes:
      - "./htdocs:/var/www/html"
    restart: always
