version: '3'
services:
  db:
    image: 'mysql:${MYSQL_VERSION}'
    entrypoint: ["docker-entrypoint.sh", "--default-authentication-plugin", "mysql_native_password", "--max-allowed-packet", "64M"]
    volumes:
      - "../volumes/mysql/data:/var/lib/mysql"
      - "../volumes/mysql/init:/docker-entrypoint-initdb.d"
    environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - "backend-tier"

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}'
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - "./container/phpmyadmin/php.ini:/etc/php5/conf.d/zzz-custom.ini"
    environment:
      MYSQL_HOST: db
      UPLOAD_SIZE: "500M"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - "backend-tier"

  php:
    depends_on:
      - db
      - phpmyadmin
      - mail
    image: 'fduarte42/docker-php:${PHP_VERSION}'
    links:
      - db:db
      - mail:mail
      - mail:mailhog
      - phpmyadmin:phpmyadmin
    volumes:
      - "./container/php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini"
      - "../volumes/php/session:/var/php/sessions"
      - "./container/php/apache2/sites-enabled:/etc/apache2/sites-enabled"
      - "~/.ssh:/ssh"
      - "./container/php/cron/crontab:/tmp/crontab"
      - "../../.env:/etc/environment"
      - "../../${HTDOCS_FOLDER}:/var/www/html"
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: phpmyadmin.${BASE_DOMAIN}, ${PHP_VIRTUAL_HOST:-""}
      APACHE_HOST: www.${BASE_DOMAIN}
      APACHE_ALIAS: ${PHP_APACHE_ALIAS:-"localhost"}
      BASE_DOMAIN: ${BASE_DOMAIN}
      DOCUMENT_ROOT: ${DOCUMENT_ROOT}
      APP_ENV: ${ENVIRONMENT}
      APPLICATION_ENVIRONMENT: ${ENVIRONMENT}
      TYPO3_CONTEXT: ${ENVIRONMENT}
      PHPMYADMIN_RESTRICTION: ${PHPMYADMIN_RESTRICTION:-"1"}
    networks:
      - "frontend-tier"
      - "backend-tier"

networks:
  frontend-tier:
    external:
      name: proxy
  backend-tier:
    driver: bridge

